# Generated by Django 5.0.6 on 2024-07-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='James', max_length=10),
            preserve_default=False,
        ),
    ]
